### ISSUE TITLE
Multiple new lines add empty unclosed <p> tags

### ISSUE THREAD

**Issue by alexsam29** [rudychung/SauSaGe#1]
In a text file with more than one new line separating paragraphs, unclosed ```<p>``` tags are added to the HTML file.  This creates an invalid HTML file.  
Example:  
  
Text File
```
Silver Blaze


I am afraid, Watson, that I shall have to go,” said Holmes, as we
sat down together to our breakfast one morning.

“Go! Where to?”





“To Dartmoor; to King’s Pyland.”
```
HTML file
```html
<h1>Silver Blaze</h1>
<p>I am afraid, Watson, that I shall have to go,” said Holmes, as we sat down together to our breakfast one morning.</p>
<p>“Go! Where to?”234423434</p>
</p>
</p>
</p>
</p>
<p>“To Dartmoor; to King’s Pyland.”</p>
```

**Comment by rudychung** [comment]
Changed else to else if in text reading code, added a condition requiring inParagraph to be true before outputting </p> to the `.html` file to prevent this behavior.
