### ISSUE TITLE
Code clean up: remove redundant condition in main.cpp (line 63)

### ISSUE THREAD

**Issue by alexsam29** [rudychung/SauSaGe#3]
You can remove the first condition and just leave the second condition as it appears to be redundant.  
  
Before:
```cpp
if (!std::filesystem::is_directory(i.path().string()) && i.path().extension().string() == ".txt") {
    texts.push_back(i.path());
}
```
After:
```cpp
if (i.path().extension().string() == ".txt") {
    texts.push_back(i.path());
}
```
 If the path is a directory, then the return value of ```i.path().extension().string()``` will be ```" "```.  It will still only execute if the file is a ```.txt``` file.

**Comment by rudychung** [comment]
The is_directory condition is to prevent a sub-directory that ends with `.txt` from passing through the if, it is placed there intentionally.
