### ISSUE TITLE
A blank HTML file is created when inputting a filename that doesn't exist.

### ISSUE THREAD

**Issue by alexsam29** [rudychung/SauSaGe#5]
When inputting a file that doesn't exist, a HTML file with nothing in the body will still be created and placed in the appropriate output folder.  
  
Example:
  
```SauSaGe -i fileThatDoesntExist```
```SauSaGe -i fileThatDoesntExist -o anotherFolder```
  
This will create ```fileThatDoesntExist.html``` and it will have nothing in the body.
```html
<!doctype html>
<html lang = "en">
<head>
<meta charset = "utf-8">
<title>fileThatdoesntexist.html</title>
<meta name = "viewport" content = "width=device-width, initial-scale=1">
</head>
<body>
</body>
</html>
```
  
  
Potential Fix:  
No file should be created.  Add a condition when getting the file path to check whether the text file exists.

**Comment by rudychung** [comment]
Added exists check to specified file path condition before creating `.html` files to address this behaviour.
